package models

import "gorm.io/gorm"

type Form struct {
	ID uint `gorm:"primaryKey"` // No auto-increment in schema based on "id INT" vs "INT NOT NULL GENERATED BY DEFAULT..."? Ah wait, schema says "id INT". It doesn't denote "GENERATED". Usually primary keys are generated. I will assume it's NOT auto-increment if the schema explicitly omitted it, or it might be input-provided. But typically for 'id' PK it is. The schema provided for 'forms' says: "id INT, ... CONSTRAINT pk_forms_id PRIMARY KEY (id)". It lacks "GENERATED BY DEFAULT AS IDENTITY". I will NOT add autoIncrement to be safe, or user might provide IDs. But wait, typically models use uint for ID.

	FormName    string    `gorm:"size:50;not null"`
	Description string    `gorm:"size:250"`
	DataTypeID  uint      `gorm:"not null"` // Added as required
	DataType    *DataType `gorm:"foreignKey:DataTypeID"`

	ServiceID *uint `gorm:"index"`
	Status    *bool `gorm:"default:null"`

	// Associations
	Service *Service `gorm:"foreignKey:ServiceID"`
}

func (Form) TableName() string {
	return "forms"
}

func CreateForm(db *gorm.DB, form *Form) (*Form, error) {
	err := db.Create(form).Error
	return form, err
}

func GetForm(db *gorm.DB, id uint) (*Form, error) {
	var form Form
	err := db.Preload("Service").First(&form, id).Error
	if err != nil {
		return nil, err
	}
	return &form, nil
}

func UpdateForm(db *gorm.DB, form *Form) error {
	return db.Save(form).Error
}

func DeleteForm(db *gorm.DB, id uint) error {
	return db.Delete(&Form{}, id).Error
}
